# Generated by Django 3.2.9 on 2021-11-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerLeague',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=200, unique=True)),
                ('meta_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SoccerTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('team_int', models.CharField(max_length=4)),
                ('team_rate', models.IntegerField()),
                ('team_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer_league.soccerleague')),
            ],
        ),
    ]
